import type {
  GetServerSideProps,
  InferGetStaticPropsType,
} from "next";
import Head from "next/head";

import { dehydrate, QueryClient } from "@tanstack/react-query";

import Header from "../Components/Header/Header";
import HeroSection from "../Components/HeroSection/HeroSection";
import OurWorkSection from "../Components/OurWorkSection/OurWorkSection";
import ProductSection from "../Components/ProductsSection/ProductSection";
import SpecialitySection from "../Components/SpecialitySection/SpecialitySection";
import AlwaysHelp from "../Components/AlwaysHelpSection/AlwaysHelp";
import ClientsSection from "../Components/ClientsSection/ClientsSection";
import ProblemForm from "../Components/ProblemForm/ProblemForm";
import Footer from "../Components/Footer/Footer";

import GetContactUsFormApi from "../Core/Api/Get/GetContactUsForm.api";


const Home = ({
  dehydratedState,
}: InferGetStaticPropsType<GetServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/Logo.svg" />
      </Head>

      <Header />
      <HeroSection />
      <OurWorkSection />
      <AlwaysHelp />
      <SpecialitySection />
      <ProductSection />
      <ClientsSection />
      <ProblemForm form={dehydratedState} />
      <Footer />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const queryClient = new QueryClient();

  await queryClient.fetchQuery(
    ["get"],
    async () => await GetContactUsFormApi()
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient).queries[0].state.data,
    },
  };
};
export default Home;
